corrida/urls.py
from django.urls import path
from . import views

app_name='corrida'

urlpatterns = [

    #aqui defines el tipo y nombre  del parametro que le mandas al view

    path('nueva/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/<int:tipo_de_espuma_id>', views.nueva_corrida, name='nueva_corrida'),

    path('add/<int:bloque_medidas_id>/', views.agrega_a_corrida, name='agregar_a_corrida'),
    path('orden/', views.orden_de_corrida, name='orden_de_corrida'),
    path('remover_elemento_corrida/<int:elemento_id>/', views.remover_elemento_corrida, name='remover_elemento_corrida'),

    path('cancelar_corrida/<int:corrida_id>/', views.cancelar_corrida, name='cancelar_corrida'),
    path('ordenes/', views.ordenes, name='ordenes'),
    path('ordenes_pendientes/', views.ordenes_pendientes, name='ordenes_pendientes'),
    path('producir_corrida/<int:corrida_id>/', views.producir_corrida, name='producir_corrida'),
    path('producir_bloques/<int:corrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    # path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloque_seleccionado/', views.producir_bloque_seleccionado, name='producir_bloque_seleccionado'),
    
    path('editar_cantidades_corrida/', views.editar_cantidades_corrida, name='editar_cantidades_corrida'),

    path('corrida_producida/<int:corrida_id>/', views.corrida_producida, name='corrida_producida'),

    path('monitoreo/<int:corrida_id>/', views.monitoreo_de_produccion, name='monitoreo'),

    path('corridas_producidas/', views.corridas_producidas, name='corridas_producidas'),

    path('inventario/', views.inventario, name='inventario'),

    path('lotes/', views.lotes, name='lotes'),

    path('lotes_pendientes/', views.lotes_pendientes, name='lotes_pendientes'),
    path('lotes_aprobados/', views.lotes_aprobados, name='lotes_aprobados'),
    path('lotes_rechazados/', views.lotes_rechazados, name='lotes_rechazados'),
    

    path('aprobar_lote/<int:lote_id>/', views.aprobar_lote, name='aprobar_lote'),

    path('dashboard/', views.dashboard_en_producion, name='dashboard'),

    path('bloques_disponibles/', views.bloques_disponibles, name='bloques_disponibles'),

    path('bloque_no_disponible/<int:bloque_id>', views.bloque_no_disponible, name='bloque_no_disponible'),
    
    path('bloque_si_disponible/<int:bloque_id>/', views.bloque_si_disponible, name='bloque_si_disponible'),

    #Ajustador de inventario
    path('ajustador/', views.ajustador, name='ajustador'),
    path('ajustador_infinito/', views.ajustador_infinito, name='ajustador_infinito'),
    path('buscador_bloques/', views.buscador_bloques, name='buscador_bloques'),

    


]

espumas/urls.py
from django.urls import path
from . import views

app_name='espumas'

urlpatterns = [
    #----PANTALLA PARA AGREGAR A ORDEN DE CORRIDA---
    #http://127.0.0.1:8000/espumas/
    path('', views.espumas, name='espumas'),

    #http://127.0.0.1:8000/espumas/respuesta
    path('respuesta', views.respuesta, name='respuesta'),


    #------CRUD MEDIDAS----
    #http://127.0.0.1:8000/espumas/medidas
    path('medidas/', views.medidas, name='medidas'),
    path('medidas/<int:tipo_id>/',views.medidas,name='medidas_filtrado'),

    #http://127.0.0.1:8000/espumas/1/
    path('<int:item_id>/',views.detalle_medidas,name='detalle_medidas'),
    #http://127.0.0.1:8000/espumas/agregarmedida
    path('agregarmedida',views.agregar_medidas,name='agregar_medidas'),
    #http://127.0.0.1:8000/espumas/editarmedida/1
    path('editarmedida/<int:id>',views.editar_medidas,name='editar_medidas'),
    #http://127.0.0.1:8000/espumas/deletemedida/1
    path('deletemedida/<int:id>',views.borrar_medidas,name='borrar_medidas'),


    #----Display y CRUD de TDE----
    #http://127.0.0.1:8000/espumas/tde/
    path('tde/', views.tde, name='tde'),
    #http://127.0.0.1:8000/espumas/tde/1/
    path('tde/<int:item_id>/',views.detalle_tde,name='detalle_tde'),
    #http://127.0.0.1:8000/espumas/agregartde
    path('agregartde',views.agregar_tde,name='agregar_tde'),
    #http://127.0.0.1:8000/espumas/editartde/1
    path('editartde/<int:id>',views.editar_tde,name='editar_tde'),
    #http://127.0.0.1:8000/espumas/deletetde/3
    path('deletetde/<int:id>',views.borrar_tde,name='borrar_tde'),
   
    #http://127.0.0.1:8000/espumas/medidas  
    path('formas/', views.formas, name='formas'),


#     path('sand1/', views.sand1, name='sand1'),
#     path('sand2/', views.sand2, name='sand2'),
#     path('checkout/',views.checkout,name='checkout'),
#     #app/numero
#     #OJO item_id es la var que declaraste en views
#     path('<int:item_id>/',views.detalle,name='detalle'),
#
#     #agregar
#     path('agregarmedida',views.agregar_medidas,name='agregar_medidas'),
#
#
#     #editar
#     # path('editar/<int:id>/', views.editar_medidas,name='editar_medidas')
#     path('editar/<int:id>',views.editar_medidas,name='editar_medidas'),
#
#     #borrar
#     path('delete/<int:id>',views.borrar_medidas,name='borrar_medidas'),
#
#
# #####
#     #sand de drop down nuevo
#     path('sand3/', views.sand3, name='sand3'),
#




    # path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    # path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
    # path('pruebadisplays', views.pruebadisplays, name='pruebadisplays'),


]

karmaproject/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.urls import path, include, re_path
#from shop import views
from espumas import views
#from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #index
    #http://127.0.0.1:8000/
    #Index esta en la espumas app
    path('',views.index,name='index'),

    path('corrida/', include('corrida.urls')),

    path('espumas/',include('espumas.urls')),







]

espumas/forms.py
from django import forms
from.models import *
from django.utils.translation import gettext_lazy as _

class medidasForm(forms.ModelForm):

    def informacion_general(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'tipo_de_espuma','tipo_de_unidad','forma','disponible','descripcion',
        'largo_frio_objetivo','ancho_frio_objetivo','alto_frio_objetivo','uso_objetivo', 'familia_de_medidas',
        ])]
    
    def parametros(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'largo_caliente_minimo','largo_caliente_parametro_bajo','largo_caliente_setting_predefinido','largo_caliente_parametro_alto','largo_caliente_maximo',
        'ancho_caliente_minimo','ancho_caliente_parametro_bajo','ancho_caliente_setting_predefinido','ancho_caliente_parametro_alto','ancho_caliente_maximo',
        'alto_caliente_minimo','alto_caliente_parametro_bajo','alto_caliente_setting_predefinido','alto_caliente_parametro_alto','alto_caliente_maximo',
        ])]
    
    class Meta:
        model = BloqueMedidas
        fields = ['tipo_de_espuma','tipo_de_unidad','forma','disponible','descripcion','familia_de_medidas','uso_objetivo', 
        'largo_frio_objetivo','ancho_frio_objetivo','alto_frio_objetivo',
        'largo_caliente_minimo','largo_caliente_parametro_bajo','largo_caliente_setting_predefinido','largo_caliente_parametro_alto','largo_caliente_maximo',
        'ancho_caliente_minimo','ancho_caliente_parametro_bajo','ancho_caliente_setting_predefinido','ancho_caliente_parametro_alto','ancho_caliente_maximo',
        'alto_caliente_minimo','alto_caliente_parametro_bajo','alto_caliente_setting_predefinido','alto_caliente_parametro_alto','alto_caliente_maximo',
        ]
        


class tdeForm(forms.ModelForm):

    class Meta:
        model = Tipos_de_Espuma
        fields = [
        'tipo_de_espuma','formulacion_o_clave','multiplicador','precio','familia',
        'retardante_flama','anti_bacterial','anti_estatica','color','elongacion','histasis','sag_factor','disponible',
        'densidad_descripcion',
        'densidad_objetivo_minima','densidad_objetivo_baja','densidad_objetivo','densidad_objetivo_alta','densidad_objetivo_maxima',
        'dureza_objetivo_minima','dureza_objetivo_baja','dureza_objetivo','dureza_objetivo_alta','dureza_objetivo_maxima',
        'flujo_de_aire_astm_minimo','flujo_de_aire_astm_bajo','flujo_de_aire_astm_objetivo','flujo_de_aire_astm_alto','flujo_de_aire_astm_maximo',
        'flujo_de_aire_campo_minimo','flujo_de_aire_campo_bajo','flujo_de_aire_campo_objetivo','flujo_de_aire_campo_alto','flujo_de_aire_campo_maximo',
        ]
        # error_messages = {
        #     'tipo_de_espuma':{
        #         'required':'este campo es requerido compa',
        #     } 
        # }

    def informacion_general(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'tipo_de_espuma','formulacion_o_clave','multiplicador','precio','familia',
        'retardante_flama','anti_bacterial','anti_estatica','color','elongacion','histasis','sag_factor','disponible',
        'densidad_descripcion',
        ])]
    
    def parametros(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'densidad_objetivo_minima','densidad_objetivo_baja','densidad_objetivo','densidad_objetivo_alta','densidad_objetivo_maxima',
        'dureza_objetivo_minima','dureza_objetivo_baja','dureza_objetivo','dureza_objetivo_alta','dureza_objetivo_maxima',
        'flujo_de_aire_astm_minimo','flujo_de_aire_astm_bajo','flujo_de_aire_astm_objetivo','flujo_de_aire_astm_alto','flujo_de_aire_astm_maximo',
        'flujo_de_aire_campo_minimo','flujo_de_aire_campo_bajo','flujo_de_aire_campo_objetivo','flujo_de_aire_campo_alto','flujo_de_aire_campo_maximo',
        ])]
    

espumas/views.py
from django.shortcuts import render
#from .forms import *

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import *
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
#from .forms import SignUpForm
#from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.template.loader import get_template
from django.template import loader
#from .models import Cantidadp
from corrida.models import Corrida, ElementoCorrida
from django.db.models import Count
from .forms import *



def index(request):
    return render(request, 'index.html')

# def espumas(request):
#     return HttpResponse('espumas Respuesta http: Hola')

def respuesta(request):
    return HttpResponse('Respuesta http: Hola')

#funcion para la corrida actual
#esta func entrega la activa=true y si no existe la crea
def _corrida_actual():
    try:
        corrida = Corrida.objects.get(pre_orden= True)
    except Corrida.DoesNotExist:
        corrida = Corrida.objects.create()
        corrida.save()
    return corrida

def espumas(request, tipo_id=0):
    if tipo_id != 0:
        bloques_medidas = BloqueMedidas.objects.filter(tipo_de_espuma=tipo_id)
    else:
        bloques_medidas = BloqueMedidas.objects.filter(tipo_de_unidad__tipo_de_unidad ="Normal").filter(disponible = True)
    corrida = _corrida_actual()
    formas= Formas.objects.all()

    try:
        elementos_corrida = ElementoCorrida.objects.filter(corrida = corrida)
    except ElementoCorrida.DoesNotExist:
        elementos_corrida = None
    context ={
        'bloques_medidas':bloques_medidas,
        'elementos_corrida': elementos_corrida,
        'formas':formas,
        'tipo_id':tipo_id,
    }
    return render(request,'espumas/espumas.html',context)



#----MEDIDAS----


def medidas(request,tipo_id=0):
    if tipo_id !=0:
        item_list = BloqueMedidas.objects.filter(tipo_de_espuma=tipo_id)
    else:
        item_list = BloqueMedidas.objects.all()
    tde_menus= Tipos_de_Espuma.objects.all()
    context ={
        'itemsFront':item_list,
        'menufront':tde_menus,
    }
    return render(request,'espumas/medidas/medidas.html',context)

def detalle_medidas(request,item_id):
    item = BloqueMedidas.objects.get(pk=item_id)
    context = {
        'itemsFront':item,
        # 'header':'blocks'
    }
    return render(request,'espumas/medidas/detallemedidas.html',context)


def agregar_medidas(request):
    form = medidasForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('espumas:medidas')

    return render(request,'espumas/medidas/agregarmedidas.html',{'form':form})


def editar_medidas(request,id):
    item = BloqueMedidas.objects.get(id=id)
    form =medidasForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('espumas:medidas')

    return render(request,'espumas/medidas/agregarmedidas.html',{'form':form,'item':item})


def borrar_medidas(request,id):
    item = BloqueMedidas.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('espumas:medidas')
    return render(request,'espumas/medidas/borrarmedidas.html',{'item':item})



#-----TIPO DE Espuma-----

def tde(request):
    item_list = Tipos_de_Espuma.objects.all()
    context ={
        'itemsFront':item_list,
    }
    return render(request,'espumas/tde/tde.html',context)

def detalle_tde(request,item_id):
    item = Tipos_de_Espuma.objects.get(pk=item_id)
    context = {
        'itemsFront':item,
        # 'header':'blocks'
    }
    return render(request,'espumas/tde/detalletde.html',context)


def agregar_tde(request):
    form = tdeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('espumas:tde')

    return render(request,'espumas/tde/agregartde.html',{'form':form})


def editar_tde(request,id):
    item = Tipos_de_Espuma.objects.get(id=id)
    form =tdeForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('espumas:tde')

    return render(request,'espumas/tde/agregartde.html',{'form':form,'item':item})


def borrar_tde(request,id):
    item = Tipos_de_Espuma.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('espumas:tde')
    return render(request,'espumas/tde/borrartde.html',{'item':item})



def formas(request):
    item_list = Formas.objects.all()
    context ={
        'itemsFront':item_list,
    }
    return render(request,'espumas/selectores/formas.html',context)

espumas/templates/espumas/medidas/agregarmedidas.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}	
<br>
<br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h2 class="text-primary">Datos Generales: </h2>
        <br>
        {% for field in form.informacion_general %}
            {% if forloop.first %}<div class="row">{% endif %}
                <div class="form-group col">
                    {{ field.label_tag }}
                    {% if form.is_bound %}
                      {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                          <div class="invalid-feedback">
                            {{ error }}
                          </div>
                        {% endfor %}
                      {% else %}
                        {% render_field field class="form-control is-valid" %}
                      {% endif %}
                    {% else %}
                      {% render_field field class="form-control" %}
                    {% endif %}
                    {% if field.help_text %}
                      <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                  </div>
            {% if forloop.counter|divisibleby:5 %}</div><div class="row">{% endif %}
            {% if forloop.last %}</div>{% endif %}
        {% endfor %}
        <br>
        <h2 class="text-primary">Parámetros: </h2>
        <br>
        {% for field in form.parametros %}
            {% if forloop.first %}<div class="row">{% endif %}
                <div class="col form-group">
                    {{ field.label_tag }}
                    {% if form.is_bound %}
                      {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                          <div class="invalid-feedback">
                            {{ error }}
                          </div>
                        {% endfor %}
                      {% else %}
                        {% render_field field class="form-control is-valid" %}
                      {% endif %}
                    {% else %}
                      {% render_field field class="form-control" %}
                    {% endif %}
                    {% if field.help_text %}
                      <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                  </div>
            {% if forloop.counter|divisibleby:5 %}</div><div class="row">{% endif %}
            {% if forloop.last %}</div>{% endif %}
        {% endfor %}
        <br>
        <button class="btn btn-success" type="submit" formnovalidate> Guardar</button>
        <a class="btn btn-primary" href="{% url 'espumas:medidas' %}" role="button"> Regresar </a>
    </form>
    <br>
</div>
{% endblock %}

espumas/templates/espumas/medidas/borrarmedidas.html
{% extends "basedetalles.html" %}
{% block content %}




<form method="POST">
    {% csrf_token %}
    <h2>
        Estas seguro que deseas borrar este bloque?
        <br>
        <br>
         
         Medidas Descripcion: <font color="green">{{ item.descripcion }}</font> - TDE:<font color="red"> {{ item.tipo_de_espuma }}</font> - Unidad: <font color="orange">{{ item.tipo_de_unidad }} </font>
         <br>
         <br>
        <button  class="btn btn-danger" type="submit"> BORRAR </button>
        <a class="btn btn-info" href="{% url 'espumas:espumas' %}" role="button"> Regresar </a>
    </h2>
</form>



{%endblock%}

espumas/templates/espumas/medidas/medidas.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-right text-secondary"><b> Medidas </b></h1>
<div class="dropdown show">
    <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Tipos De Espuma
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        {% for menuItem in menufront %}
        <a class="dropdown-item"  href="{% url 'espumas:medidas_filtrado' menuItem.id %}"> {{menuItem}}</a>
        {% endfor %}  
    </div>
    <a class="btn btn-success" href="{% url 'espumas:agregar_medidas' %}" role="button"> Agregar Medidas </a>
</div>
<br>
<table class="table table-hover" >
        <thead>
          <tr>
            <th class="text-center"><b> Tipo espuma </b></th>
            <th class="text-center"><b> Medidas Descripcion </b></th>
            <th class="text-center"><b> Familia </b></th>
            <th class="text-center"><b> Forma </b></th>
            <th class="text-center"><b> Tipo de Unidad </b></th>
            <th class="text-center"><b> Editar </b></th>
            <th class="text-center"><b> Borrar </b></th>
            <th class="text-center"><b> Ver Detalles </b></th>
          </tr>
        </thead>
        <tbody>
            {% for item in itemsFront%}
        <tr>
            <td class="text-center">{{ item.tipo_de_espuma }}</td>
            <td class="text-center"><a href="{% url 'espumas:detalle_medidas' item.id %} "> {{ item.descripcion}} </a></td>
            {% if item.familia_de_medidas %}
                <td class="text-center align-middle">   {{ item.familia_de_medidas }} </td>
            {% else %}
                <td class="text-center align-middle" > <font color="red"> X </font> </td>
            {%endif%}
            <td class="text-center">{{ item.forma }}</td>
            <td class="text-center">{{ item.tipo_de_unidad }}</td>
            <td class="text-center"><a class="btn btn-warning" href="{% url 'espumas:editar_medidas' item.id %}" role="button"> editar  </a></td>
            <td class="text-center"><a class="btn btn-danger" href="{% url 'espumas:borrar_medidas' item.id %}" role="button"> Borrar </a></td>
            <td class="text-center"><a class="btn btn-primary" href="{% url 'espumas:detalle_medidas' item.id %}" role="button"> Ver A Detalle </a></td>
                {% endfor %}
        </tr>
        </tbody>
    </table>
    <br>
    <br>
    {% endblock %}