corrida/urls.py
from django.urls import path
from . import views

app_name='corrida'

urlpatterns = [

    #aqui defines el tipo y nombre  del parametro que le mandas al view

    path('nueva/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/<int:tipo_de_espuma_id>', views.nueva_corrida, name='nueva_corrida'),

    path('add/<int:bloque_medidas_id>/', views.agrega_a_corrida, name='agregar_a_corrida'),
    path('orden/', views.orden_de_corrida, name='orden_de_corrida'),
    path('remover_elemento_corrida/<int:elemento_id>/', views.remover_elemento_corrida, name='remover_elemento_corrida'),

    path('cancelar_corrida/<int:corrida_id>/', views.cancelar_corrida, name='cancelar_corrida'),
    path('ordenes/', views.ordenes, name='ordenes'),
    path('ordenes_pendientes/', views.ordenes_pendientes, name='ordenes_pendientes'),
    path('producir_corrida/<int:corrida_id>/', views.producir_corrida, name='producir_corrida'),
    path('producir_bloques/<int:corrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    # path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloque_seleccionado/', views.producir_bloque_seleccionado, name='producir_bloque_seleccionado'),
    
    path('editar_cantidades_corrida/', views.editar_cantidades_corrida, name='editar_cantidades_corrida'),

    path('corrida_producida/<int:corrida_id>/', views.corrida_producida, name='corrida_producida'),

    path('monitoreo/<int:corrida_id>/', views.monitoreo_de_produccion, name='monitoreo'),

    path('corridas_producidas/', views.corridas_producidas, name='corridas_producidas'),

    path('inventario/', views.inventario, name='inventario'),

    path('lotes/', views.lotes, name='lotes'),

    path('lotes_pendientes/', views.lotes_pendientes, name='lotes_pendientes'),
    path('lotes_aprobados/', views.lotes_aprobados, name='lotes_aprobados'),
    path('lotes_rechazados/', views.lotes_rechazados, name='lotes_rechazados'),
    

    path('aprobar_lote/<int:lote_id>/', views.aprobar_lote, name='aprobar_lote'),

    path('dashboard/', views.dashboard_en_producion, name='dashboard'),

    path('bloques_disponibles/', views.bloques_disponibles, name='bloques_disponibles'),

    path('bloque_no_disponible/<int:bloque_id>', views.bloque_no_disponible, name='bloque_no_disponible'),
    
    path('bloque_si_disponible/<int:bloque_id>/', views.bloque_si_disponible, name='bloque_si_disponible'),

    #Ajustador de inventario
    path('ajustador/', views.ajustador, name='ajustador'),
    path('ajustador_infinito/', views.ajustador_infinito, name='ajustador_infinito'),
    path('buscador_bloques/', views.buscador_bloques, name='buscador_bloques'),

    


]

espumas/urls.py
from django.urls import path
from . import views

app_name='espumas'

urlpatterns = [
    #----PANTALLA PARA AGREGAR A ORDEN DE CORRIDA---
    #http://127.0.0.1:8000/espumas/
    path('', views.espumas, name='espumas'),

    #http://127.0.0.1:8000/espumas/respuesta
    path('respuesta', views.respuesta, name='respuesta'),


    #------CRUD MEDIDAS----
    #http://127.0.0.1:8000/espumas/medidas
    path('medidas/', views.medidas, name='medidas'),
    path('medidas/<int:tipo_id>/',views.medidas,name='medidas_filtrado'),

    #http://127.0.0.1:8000/espumas/1/
    path('<int:item_id>/',views.detalle_medidas,name='detalle_medidas'),
    #http://127.0.0.1:8000/espumas/agregarmedida
    path('agregarmedida',views.agregar_medidas,name='agregar_medidas'),
    #http://127.0.0.1:8000/espumas/editarmedida/1
    path('editarmedida/<int:id>',views.editar_medidas,name='editar_medidas'),
    #http://127.0.0.1:8000/espumas/deletemedida/1
    path('deletemedida/<int:id>',views.borrar_medidas,name='borrar_medidas'),


    #----Display y CRUD de TDE----
    #http://127.0.0.1:8000/espumas/tde/
    path('tde/', views.tde, name='tde'),
    #http://127.0.0.1:8000/espumas/tde/1/
    path('tde/<int:item_id>/',views.detalle_tde,name='detalle_tde'),
    #http://127.0.0.1:8000/espumas/agregartde
    path('agregartde',views.agregar_tde,name='agregar_tde'),
    #http://127.0.0.1:8000/espumas/editartde/1
    path('editartde/<int:id>',views.editar_tde,name='editar_tde'),
    #http://127.0.0.1:8000/espumas/deletetde/3
    path('deletetde/<int:id>',views.borrar_tde,name='borrar_tde'),
   
    #http://127.0.0.1:8000/espumas/medidas  
    path('formas/', views.formas, name='formas'),


#     path('sand1/', views.sand1, name='sand1'),
#     path('sand2/', views.sand2, name='sand2'),
#     path('checkout/',views.checkout,name='checkout'),
#     #app/numero
#     #OJO item_id es la var que declaraste en views
#     path('<int:item_id>/',views.detalle,name='detalle'),
#
#     #agregar
#     path('agregarmedida',views.agregar_medidas,name='agregar_medidas'),
#
#
#     #editar
#     # path('editar/<int:id>/', views.editar_medidas,name='editar_medidas')
#     path('editar/<int:id>',views.editar_medidas,name='editar_medidas'),
#
#     #borrar
#     path('delete/<int:id>',views.borrar_medidas,name='borrar_medidas'),
#
#
# #####
#     #sand de drop down nuevo
#     path('sand3/', views.sand3, name='sand3'),
#




    # path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    # path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
    # path('pruebadisplays', views.pruebadisplays, name='pruebadisplays'),


]

karmaproject/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.urls import path, include, re_path
#from shop import views
from espumas import views
#from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #index
    #http://127.0.0.1:8000/
    #Index esta en la espumas app
    path('',views.index,name='index'),

    path('corrida/', include('corrida.urls')),

    path('espumas/',include('espumas.urls')),







]

espumas/forms.py
from django import forms
from.models import *
from django.utils.translation import gettext_lazy as _

class medidasForm(forms.ModelForm):

    def informacion_general(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'tipo_de_espuma','tipo_de_unidad','forma','disponible','descripcion',
        'largo_frio_objetivo','ancho_frio_objetivo','alto_frio_objetivo','uso_objetivo', 'familia_de_medidas',
        ])]
    
    def parametros(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'largo_caliente_minimo','largo_caliente_parametro_bajo','largo_caliente_setting_predefinido','largo_caliente_parametro_alto','largo_caliente_maximo',
        'ancho_caliente_minimo','ancho_caliente_parametro_bajo','ancho_caliente_setting_predefinido','ancho_caliente_parametro_alto','ancho_caliente_maximo',
        'alto_caliente_minimo','alto_caliente_parametro_bajo','alto_caliente_setting_predefinido','alto_caliente_parametro_alto','alto_caliente_maximo',
        ])]
    
    class Meta:
        model = BloqueMedidas
        fields = ['tipo_de_espuma','tipo_de_unidad','forma','disponible','descripcion','familia_de_medidas','uso_objetivo', 
        'largo_frio_objetivo','ancho_frio_objetivo','alto_frio_objetivo',
        'largo_caliente_minimo','largo_caliente_parametro_bajo','largo_caliente_setting_predefinido','largo_caliente_parametro_alto','largo_caliente_maximo',
        'ancho_caliente_minimo','ancho_caliente_parametro_bajo','ancho_caliente_setting_predefinido','ancho_caliente_parametro_alto','ancho_caliente_maximo',
        'alto_caliente_minimo','alto_caliente_parametro_bajo','alto_caliente_setting_predefinido','alto_caliente_parametro_alto','alto_caliente_maximo',
        ]
        


class tdeForm(forms.ModelForm):

    class Meta:
        model = Tipos_de_Espuma
        fields = [
        'tipo_de_espuma','formulacion_o_clave','multiplicador','precio','familia',
        'retardante_flama','anti_bacterial','anti_estatica','color','elongacion','histasis','sag_factor','disponible',
        'densidad_descripcion',
        'densidad_objetivo_minima','densidad_objetivo_baja','densidad_objetivo','densidad_objetivo_alta','densidad_objetivo_maxima',
        'dureza_objetivo_minima','dureza_objetivo_baja','dureza_objetivo','dureza_objetivo_alta','dureza_objetivo_maxima',
        'flujo_de_aire_astm_minimo','flujo_de_aire_astm_bajo','flujo_de_aire_astm_objetivo','flujo_de_aire_astm_alto','flujo_de_aire_astm_maximo',
        'flujo_de_aire_campo_minimo','flujo_de_aire_campo_bajo','flujo_de_aire_campo_objetivo','flujo_de_aire_campo_alto','flujo_de_aire_campo_maximo',
        ]
        # error_messages = {
        #     'tipo_de_espuma':{
        #         'required':'este campo es requerido compa',
        #     } 
        # }

    def informacion_general(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'tipo_de_espuma','formulacion_o_clave','multiplicador','precio','familia',
        'retardante_flama','anti_bacterial','anti_estatica','color','elongacion','histasis','sag_factor','disponible',
        'densidad_descripcion',
        ])]
    
    def parametros(self):
        fields = self.visible_fields()
        return [field for field in fields if (field.name in [
        'densidad_objetivo_minima','densidad_objetivo_baja','densidad_objetivo','densidad_objetivo_alta','densidad_objetivo_maxima',
        'dureza_objetivo_minima','dureza_objetivo_baja','dureza_objetivo','dureza_objetivo_alta','dureza_objetivo_maxima',
        'flujo_de_aire_astm_minimo','flujo_de_aire_astm_bajo','flujo_de_aire_astm_objetivo','flujo_de_aire_astm_alto','flujo_de_aire_astm_maximo',
        'flujo_de_aire_campo_minimo','flujo_de_aire_campo_bajo','flujo_de_aire_campo_objetivo','flujo_de_aire_campo_alto','flujo_de_aire_campo_maximo',
        ])]
    

espumas/views.py
from django.shortcuts import render
#from .forms import *

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import *
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
#from .forms import SignUpForm
#from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.template.loader import get_template
from django.template import loader
#from .models import Cantidadp
from corrida.models import Corrida, ElementoCorrida
from django.db.models import Count
from .forms import *



def index(request):
    return render(request, 'index.html')

# def espumas(request):
#     return HttpResponse('espumas Respuesta http: Hola')

def respuesta(request):
    return HttpResponse('Respuesta http: Hola')

#funcion para la corrida actual
#esta func entrega la activa=true y si no existe la crea
def _corrida_actual():
    try:
        corrida = Corrida.objects.get(pre_orden= True)
    except Corrida.DoesNotExist:
        corrida = Corrida.objects.create()
        corrida.save()
    return corrida

def espumas(request, tipo_id=0):
    if tipo_id != 0:
        bloques_medidas = BloqueMedidas.objects.filter(tipo_de_espuma=tipo_id)
    else:
        bloques_medidas = BloqueMedidas.objects.filter(tipo_de_unidad__tipo_de_unidad ="Normal").filter(disponible = True)
    corrida = _corrida_actual()
    formas= Formas.objects.all()

    try:
        elementos_corrida = ElementoCorrida.objects.filter(corrida = corrida)
    except ElementoCorrida.DoesNotExist:
        elementos_corrida = None
    context ={
        'bloques_medidas':bloques_medidas,
        'elementos_corrida': elementos_corrida,
        'formas':formas,
        'tipo_id':tipo_id,
    }
    return render(request,'espumas/espumas.html',context)



#----MEDIDAS----


def medidas(request,tipo_id=0):
    if tipo_id !=0:
        item_list = BloqueMedidas.objects.filter(tipo_de_espuma=tipo_id)
    else:
        item_list = BloqueMedidas.objects.all()
    tde_menus= Tipos_de_Espuma.objects.all()
    context ={
        'itemsFront':item_list,
        'menufront':tde_menus,
    }
    return render(request,'espumas/medidas/medidas.html',context)

def detalle_medidas(request,item_id):
    item = BloqueMedidas.objects.get(pk=item_id)
    context = {
        'itemsFront':item,
        # 'header':'blocks'
    }
    return render(request,'espumas/medidas/detallemedidas.html',context)


def agregar_medidas(request):
    form = medidasForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('espumas:medidas')

    return render(request,'espumas/medidas/agregarmedidas.html',{'form':form})


def editar_medidas(request,id):
    item = BloqueMedidas.objects.get(id=id)
    form =medidasForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('espumas:medidas')

    return render(request,'espumas/medidas/agregarmedidas.html',{'form':form,'item':item})


def borrar_medidas(request,id):
    item = BloqueMedidas.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('espumas:medidas')
    return render(request,'espumas/medidas/borrarmedidas.html',{'item':item})



#-----TIPO DE Espuma-----

def tde(request):
    item_list = Tipos_de_Espuma.objects.all()
    context ={
        'itemsFront':item_list,
    }
    return render(request,'espumas/tde/tde.html',context)

def detalle_tde(request,item_id):
    item = Tipos_de_Espuma.objects.get(pk=item_id)
    context = {
        'itemsFront':item,
        # 'header':'blocks'
    }
    return render(request,'espumas/tde/detalletde.html',context)


def agregar_tde(request):
    form = tdeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('espumas:tde')

    return render(request,'espumas/tde/agregartde.html',{'form':form})


def editar_tde(request,id):
    item = Tipos_de_Espuma.objects.get(id=id)
    form =tdeForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('espumas:tde')

    return render(request,'espumas/tde/agregartde.html',{'form':form,'item':item})


def borrar_tde(request,id):
    item = Tipos_de_Espuma.objects.get(id=id)

    if request.method =='POST':
        item.delete()
        return redirect('espumas:tde')
    return render(request,'espumas/tde/borrartde.html',{'item':item})



def formas(request):
    item_list = Formas.objects.all()
    context ={
        'itemsFront':item_list,
    }
    return render(request,'espumas/selectores/formas.html',context)

espumas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">

	<title>Espumas </title>
</head>
<body>
	<div class="container">


		{% include 'header.html' %}
		
		{% block content %}
		{% endblock %}
	</div>
		{% include 'footer.html' %}
		<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
   		<script src="{% static 'js/popper.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

espumas/templates/base_datatable.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/ju-1.12.1/jq-3.3.1/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-flash-1.6.1/b-html5-1.6.1/b-print-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sc-2.0.1/sp-1.0.1/sl-1.3.1/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/ju-1.12.1/jq-3.3.1/jszip-2.5.0/dt-1.10.20/af-2.3.4/b-1.6.1/b-colvis-1.6.1/b-flash-1.6.1/b-html5-1.6.1/b-print-1.6.1/cr-1.5.2/fc-3.3.0/fh-3.1.6/kt-2.5.1/r-2.2.3/rg-1.1.1/rr-1.2.6/sc-2.0.1/sp-1.0.1/sl-1.3.1/datatables.min.js"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<title>Espumas </title>
</head>
<body>
	


		{% include 'header.html' %}
		
		{% block content %}
		{% endblock %}

		{% include 'footer.html' %}
	
</body>
</html>

espumas/templates/base_izq.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">

	<title>Espumas </title>
</head>
<body>
	<div class="container ml-3 ">


		{% include 'header.html' %}
		
		{% block content %}
		{% endblock %}
	</div>
		{% include 'footer.html' %}
		<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
   		<script src="{% static 'js/popper.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

espumas/templates/basedetalles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">

	<title>Detalles </title>
</head>
<body>
	<div class="container">


		<br>
		<br>
		
		{% block content %}
		{% endblock %}
	</div>
		
		<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
   		<script src="{% static 'js/popper.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

espumas/templates/baseprod.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">

	<title> Producción de Espumado </title>
</head>
<body>
	

        <header>
                <br>
                <center>
                    
                    <a href="{% url 'index' %}"><img src="{% static 'img/logo_espumas.png' %}" ></a>
                </center>
            </header>
		
		
        {% block content %}
        
		{% endblock %}
	
		{% include 'footer.html' %}
		<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
   		<script src="{% static 'js/popper.min.js' %}"></script>
    	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

espumas/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
        <p class="text-center">&copy; Espumas. 2020.</p>
    </div>
    

espumas/templates/header.html
{% load static %}
<header>
	<br>
	<center>
		
		<a href="{% url 'index' %}"><img src="{% static 'img/logo_espumas.png' %}" ></a>
	</center>
</header>

espumas/templates/index.html
{% extends "base.html" %}
{% block content %}

<br>
<br>

<div class="container">
		<main role="main">

						<!-- Main jumbotron for a primary marketing message or call to action -->
						<div class="jumbotron">
							<div class="container">
								<h1 class="display-3">Bienvenido a Espumas</h1>
								<p>Bienvenido al sitio de producción e inventario de Espumas.</p>
								<p><a class="btn btn-primary btn-lg" href="https://docs.google.com/document/d/1Qiu6f-SoOruCKVwTFUUgwhWwazacUHapCJS3SGV9vLU/edit?usp=sharing" role="button">Documentacion &raquo;</a></p>
							</div>
						</div>

						<div class="container">
							<!-- Example row of columns -->
							<div class="row">
								<div class="col-md-4">
									<h2>Tipos De Espuma</h2>
									<p>Esta es la sección donde ven, agregan o modifican los un tipos de espuma.</p>
									<p><a class="btn btn-primary" href="{% url 'espumas:tde' %}" role="button">  Tipos De Espuma &raquo;</a></p>
								</div>
								<div class="col-md-4">
									<h2>Bloques/Medidas</h2>
									<p>Esta es la sección donde se seleciona un los bloques para producir una orden de corrida.</p>
									<p><a class="btn btn-primary" href="{% url 'espumas:medidas' %}" role="button"> Bloques/Medidas &raquo;</a></p>
								</div>
								<div class="col-md-4">
									<h2>Generar Corrida</h2>
									<p>Esta es la sección donde se puede ver el catalogo de espumas y bloques para generar una corrida.</p>
									<p><a class="btn btn-primary" href="{% url 'espumas:formas' %}" role="button"> Generar Corrida &raquo;</a></p>
								</div>
							</div>
							
							<br>

							<div class="row">
										<div class="col-md-4">
											<h2> Inventario </h2>
											<p> Para ver inventario, generar reportes o buscar una pieza entre aquí.</p>
											<p><a class="btn btn-primary" href="https://espumasmonterrey.com/" role="button">Ver Inventario  &raquo;</a></p>										</div>
										<div class="col-md-4">
											<h2>Ordenes Pendientes</h2>
											<p> Aqui se revisan las ordenes pendientes antes y durante producción.</p>
											<p><a class="btn btn-primary" href="{% url 'corrida:ordenes_pendientes' %}" role="button"> Ver Ordenes Pendientes &raquo;</a></p>
										</div>
										<div class="col-md-4">
											<h2>Ordenes Producidas</h2>
											
											<p>Para ver las ordenes producidas entre aquí.</p>
											<p><a class="btn btn-primary" href="{% url 'corrida:corridas_producidas' %}" role="button"> Ver Ordenes Producidas &raquo;</a></p>
										</div>
									</div>

									<br>

									<div class="row">
												<div class="col-md-4">
													<h2> Peeler </h2>
													<p> Para Ir a Peeler, se requiere de usario y contrasena.</p>
													<p><a class="btn btn-primary" href="https://espumasmonterrey.com/" role="button">Ir A Peeler  &raquo;</a></p>
												</div>
												<div class="col-md-4">
													<h2> DashBoard</h2>
													<p> Para ver el DashBoard de producion de espuma entra aquí.</p>
													<p><a class="btn btn-primary" href="{% url 'corrida:dashboard' %}" role="button">Ver DashBoard &raquo;</a></p>
												</div>
												<div class="col-md-4">
													<h2> Bloques disponibles </h2>
													<p> Buscador de bloques por lote, aqui puedes habilitar o des habilitar la disponibilidad.</p>
													<p><a class="btn btn-primary" href="{% url 'corrida:buscador_bloques' %}" role="button"> Ver Bloques disponibles &raquo;</a></p>
												</div>
											</div>

											<br>

											<div class="row">
														<div class="col-md-4">
															<h2>Laboratorio</h2>
															<p> Aqui se aprueban las pruebas de Laboratorio</p>
															<p><a class="btn btn-primary" href="{% url 'corrida:lotes' %}" role="button">Ir A Laboratorio &raquo;</a></p>
														</div>
														<div class="col-md-4">
															<h2>Reportes de Fallas</h2>
															<p> Para ver los reportes de fallas generados entra aquí.</p>
															<p><a class="btn btn-primary" href="https://espumasmonterrey.com/" role="button">Ver Reportes de Fallas &raquo;</a></p>
														</div>
														<div class="col-md-4">
															<h2>Inteligencia de Negocios </h2>
															<p> Para ver las estadísticas e inteligencia de negocios entra aquí.</p>
															<p><a class="btn btn-primary" href="https://espumasmonterrey.com/" role="button">Inteligencia de Negocios &raquo;</a></p>
														</div>
													</div>

													<br>

													
														{% endblock %}