corrida/urls.py
from django.urls import path
from . import views

app_name='corrida'

urlpatterns = [

    #aqui defines el tipo y nombre  del parametro que le mandas al view

    path('nueva/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/', views.nueva_corrida, name='nueva_corrida'),
    path('nueva/<int:forma_id>/<int:tipo_de_espuma_id>', views.nueva_corrida, name='nueva_corrida'),

    path('add/<int:bloque_medidas_id>/', views.agrega_a_corrida, name='agregar_a_corrida'),
    path('orden/', views.orden_de_corrida, name='orden_de_corrida'),
    path('remover_elemento_corrida/<int:elemento_id>/', views.remover_elemento_corrida, name='remover_elemento_corrida'),

    path('cancelar_corrida/<int:corrida_id>/', views.cancelar_corrida, name='cancelar_corrida'),
    path('ordenes/', views.ordenes, name='ordenes'),
    path('ordenes_pendientes/', views.ordenes_pendientes, name='ordenes_pendientes'),
    path('producir_corrida/<int:corrida_id>/', views.producir_corrida, name='producir_corrida'),
    path('producir_bloques/<int:corrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    # path('producir_bloques/<int:corrida_id>/<int:elementoCorrida_id>/', views.producir_bloques, name='producir_bloques'),
    path('producir_bloque_seleccionado/', views.producir_bloque_seleccionado, name='producir_bloque_seleccionado'),
    
    path('editar_cantidades_corrida/', views.editar_cantidades_corrida, name='editar_cantidades_corrida'),

    path('corrida_producida/<int:corrida_id>/', views.corrida_producida, name='corrida_producida'),

    path('monitoreo/<int:corrida_id>/', views.monitoreo_de_produccion, name='monitoreo'),

    path('corridas_producidas/', views.corridas_producidas, name='corridas_producidas'),

    path('inventario/', views.inventario, name='inventario'),

    path('lotes/', views.lotes, name='lotes'),

    path('lotes_pendientes/', views.lotes_pendientes, name='lotes_pendientes'),
    path('lotes_aprobados/', views.lotes_aprobados, name='lotes_aprobados'),
    path('lotes_rechazados/', views.lotes_rechazados, name='lotes_rechazados'),
    

    path('aprobar_lote/<int:lote_id>/', views.aprobar_lote, name='aprobar_lote'),

    path('dashboard/', views.dashboard_en_producion, name='dashboard'),

    path('bloques_disponibles/', views.bloques_disponibles, name='bloques_disponibles'),

    path('bloque_no_disponible/<int:bloque_id>', views.bloque_no_disponible, name='bloque_no_disponible'),
    
    path('bloque_si_disponible/<int:bloque_id>/', views.bloque_si_disponible, name='bloque_si_disponible'),

    #Ajustador de inventario
    path('ajustador/', views.ajustador, name='ajustador'),
    path('ajustador_infinito/', views.ajustador_infinito, name='ajustador_infinito'),
    path('buscador_bloques/', views.buscador_bloques, name='buscador_bloques'),

    


]

karmaproject/urls.py
from django.contrib import admin
from django.urls import include ,path
from django.urls import path, include, re_path
#from shop import views
from espumas import views
#from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #index
    #http://127.0.0.1:8000/
    #Index esta en la espumas app
    path('',views.index,name='index'),

    path('corrida/', include('corrida.urls')),

    path('espumas/',include('espumas.urls')),







]

corrida/models.py
from django.db import models
from espumas.models import BloqueMedidas
from django.db.models import Sum
import datetime
from decimal import *

class Corrida(models.Model):
	CEDIS_CHOICES=[
		('Monterrey', 'Monterrey'),
        ('Salinas', 'Salinas'),
	]

	#corrida_id = models.CharField(max_length=250, blank=True)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	fecha_programada = models.DateTimeField(null = True)
	fecha_creacion = models.DateTimeField(null = True)
	fecha_produccion = models.DateTimeField(null = True)
	pre_orden = models.BooleanField(default = True)
	pendiente_produccion = models.BooleanField(default = False)
	en_produccion = models.BooleanField(default = False)
	cancelada = models.BooleanField(default = False)
	producto_terminado = models.BooleanField(default = False)
	cedis = models.CharField(max_length=122,choices=CEDIS_CHOICES, default='Monterrey')
	
	class Meta:
		db_table = 'Corrida'
		ordering = ['-id']

	def area_de_curado_estimada(self):
		elementos = self.elementocorrida_set.all()
		area_total = 0
		for elemento in elementos:
			largo = float(elemento.bloqueMedidas.largo_caliente_setting_predefinido) or 0
			ancho = float(elemento.bloqueMedidas.ancho_caliente_setting_predefinido)or 0
			area_bloque = ((largo/100) + 0.1) * ((ancho/100) + 0.1)
			area_elemento = area_bloque * elemento.cantidad
			area_total = area_total + area_elemento
		
		return round(area_total,2)

	def area_de_curado(self):
		elementos = self.elementocorrida_set.all()
		area_total = 0
		for elemento in elementos:
			area_elemento = elemento.area_de_curado()
			area_total = area_total + area_elemento
		return round(area_total,2)


	def total_de_bloques(self):
		return ElementoCorrida.objects.filter(corrida = self).aggregate(Sum('cantidad'))

	def __str__(self):
		return str(self.pk)

class Lote(models.Model):	
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	no_de_lote = models.CharField(max_length = 100)
	dureza_capturada = models.DecimalField(max_digits = 10, decimal_places = 2, null = True, default= 0)
	sag_factor_capturado = models.DecimalField(max_digits = 10, decimal_places = 2, null = True, default= 0)
	densidad_capturada = models.DecimalField(max_digits = 10, decimal_places = 2, null = True, default= 0)
	flujo_de_aire_astm_capturado = models.DecimalField(max_digits = 10, decimal_places = 2, null = True, default= 0)
	pruebas_realizadas = models.BooleanField(default = False)
	pruebas_pasadas = models.BooleanField(default = False)
	


	class Meta:
		db_table = 'Lote'
		# ordering = ['']

	def __str__(self):
		return str(self.no_de_lote)



class ElementoCorrida(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now = True)
	lote = models.ForeignKey(Lote, on_delete=models.CASCADE, null= True)
	bloqueMedidas = models.ForeignKey(BloqueMedidas, on_delete = models.CASCADE)
	corrida = models.ForeignKey(Corrida, on_delete = models.CASCADE)
	cantidad = models.IntegerField()
	# turno = models.IntegerField()
	#active = models.BooleanField(default=True)

	class Meta:
		db_table = 'ElementoCorrida'
		ordering = ['lote']

	def sub_total(self):
		return self.bloqueMedidas.price * self.cantidad

	def bloques_producidos(self):
		return self.bloqueproducido_set.all().count()

	def area_de_curado(self):
		bloques = self.bloqueproducido_set.all()
		area_total = 0
		bloques_count = bloques.count()
		margen_lineal = bloques_count * 0.1
		largo_total = float(bloques.aggregate(sum=Sum('largo_caliente'))['sum'] or 0)
		ancho_total = float(bloques.aggregate(sum=Sum('ancho_caliente'))['sum'] or 0)
		area_total = ((largo_total/100)+(margen_lineal)) *((ancho_total/100)+(margen_lineal))

		return area_total

	def metros_lineales_individuales(self):
		return self.bloqueMedidas.largo_frio_objetivo * self.cantidad

	def __str__(self):
		return '{0} {1},{2}'.format( self.bloqueMedidas.tipo_de_espuma, self.bloqueMedidas.descripcion, self.bloqueMedidas.tipo_de_unidad)





class BloqueProducido(models.Model):
	
	DEFECTOS_CHOICES=[
		('sd', ''),
		('ph','Pinhole'),
		('g', 'Grieta'),
		('v', 'Vena'),
		('mm','Mal manejo'),
		('fm', 'Fuera de medida'),
		('a', 'Algodonozo'),
		('ma', 'Manchado'),
	]

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now = True)
	no_de_bloque = models.IntegerField(default=1)
	elemento_corrida = models.ForeignKey(ElementoCorrida, on_delete = models.CASCADE)
	revision_calidad = models.BooleanField(default=True)
	defecto = models.CharField(max_length=2,choices=DEFECTOS_CHOICES, default='sd')
	largo_caliente = models.DecimalField(max_digits=10, decimal_places=2 ,null = True, default = 122,blank = True )
	ancho_caliente = models.DecimalField(max_digits=10, decimal_places=2,null = True,default = 122 ,blank = True)
	alto_caliente = models.DecimalField(max_digits=10, decimal_places=2,null = True , default = 122,blank = True )
	flujo_de_aire_caliente = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank = True)
	peso_caliente = models.DecimalField(max_digits=10, decimal_places=2)
	comentario = models.CharField(max_length =300,blank = True,null=True)
	volumen = models.DecimalField(max_digits=10, decimal_places=2,  blank= True, null = True)
	densidad = models.DecimalField(max_digits=10, decimal_places=2, blank= True, null = True)
	disponible = models.BooleanField(default=True)

	class Meta:
		db_table = 'BloqueProducido'
	
	def save(self, *args, **kwargs):
		# no_de_bloque
		bloques_en_corrida = BloqueProducido.objects.filter(elemento_corrida__corrida_id = self.elemento_corrida.corrida_id).count()
		self.no_de_bloque = bloques_en_corrida + 1
		elemento_corrida = self.elemento_corrida
		# lote
		bloques_en_elemento_corrida = BloqueProducido.objects.filter(elemento_corrida_id = elemento_corrida.id).count()
		if bloques_en_elemento_corrida == 0:
			elemento_corrida_con_lote = ElementoCorrida.objects.filter(corrida_id = elemento_corrida.corrida_id).filter(bloqueMedidas__familia_de_medidas = elemento_corrida.bloqueMedidas.familia_de_medidas).exclude(lote__isnull=True)
			if elemento_corrida_con_lote:
				
				lote = elemento_corrida_con_lote[0].lote
			else:
				meses = {"1":"L", "2":"U", "3":"I", "4":"S", "5":"V", "6":"G", "7":"A", "8":"R", "9":"C", "10":"M", "11":"T", "12":"Z"}
				today = datetime.datetime.today()
				letra = meses[str(today.month)]
				year = str(today.year)[-2:]
				tipo_de_espuma = self.elemento_corrida.bloqueMedidas.tipo_de_espuma
				corrida = self.elemento_corrida.corrida
				corridas_en_dia = BloqueProducido.objects.filter(created__date = today).distinct('elemento_corrida__corrida_id').count() 
				if not corridas_en_dia:
					corridas_en_dia = 1
				consecutivo_anual = Corrida.objects.filter(producto_terminado = True).filter( created__year = today.year).count() + 1
				# cifrado/(3dig cons anual)(1dig #corrida)/TDE/
				no_de_lote = '{0}{1}{2}/{3:03d}{4}/{5}'.format(letra, today.day, year, consecutivo_anual, corridas_en_dia, tipo_de_espuma)
				lote = Lote.objects.create(
						no_de_lote = no_de_lote
				)
				lote.save()
			elemento_corrida.lote_id = lote.id
			elemento_corrida.save()
		
		# volumen
		if self.elemento_corrida.bloqueMedidas.forma.forma == "Cilindro":
			radio = float(self.ancho_caliente)/2
			area = (radio * radio * 3.1415)
			volumen = round((float(self.largo_caliente) * area)/1000000, 2)
		else:
			volumen = round((float(self.largo_caliente) * float(self.ancho_caliente) * float(self.alto_caliente))/(1000000),2)
		self.volumen = volumen

		# densidad
		peso = float(self.peso_caliente)
		densidad = round((peso) / (volumen),2)
		self.densidad = densidad

		# save
		super().save(*args, **kwargs)

	def densidad_class(self):
		tipo_de_espuma =  self.elemento_corrida.bloqueMedidas.tipo_de_espuma
		maxima = tipo_de_espuma.densidad_objetivo_maxima
		minima = tipo_de_espuma.densidad_objetivo_minima
		alta = tipo_de_espuma.densidad_objetivo_alta
		baja = tipo_de_espuma.densidad_objetivo_baja
		amarillo = 'warning'
		gris = 'secondary'
		rojo = 'danger'
		color_class = ''

		if maxima and minima and alta and baja:
			if self.densidad >= baja and self.densidad <= alta:
				color_class = ''
			if (self.densidad >= minima and self.densidad < baja) or (self.densidad > alta and self.densidad <= maxima):
				color = amarillo
				color_class ='badge badge-{0} badge-pill'.format(color)
			if self.densidad < minima or self.densidad > maxima:
				color = rojo
				color_class ='badge badge-{0} badge-pill'.format(color)
		
		return color_class


	def largo_caliente_class(self):
		bloqueMedidas =  self.elemento_corrida.bloqueMedidas
		maxima = bloqueMedidas.largo_caliente_maximo
		minima = bloqueMedidas.largo_caliente_minimo
		alta = bloqueMedidas.largo_caliente_parametro_alto
		baja = bloqueMedidas.largo_caliente_parametro_bajo
		amarillo = 'warning'
		gris = 'secondary'
		rojo = 'danger'
		color_class = ''
	
		if maxima and minima and alta and baja:
			if self.largo_caliente >= baja and self.largo_caliente <= alta:
				color_class = ''
			if (self.largo_caliente >= minima and self.largo_caliente < baja) or (self.largo_caliente > alta and self.largo_caliente <= maxima):
				color = amarillo
				color_class ='badge badge-{0} badge-pill'.format(color)
			if self.largo_caliente < minima or self.largo_caliente > maxima:
				color = rojo
				color_class ='badge badge-{0} badge-pill'.format(color)
		
		return color_class

	
	def ancho_caliente_class(self):
		bloqueMedidas =  self.elemento_corrida.bloqueMedidas
		maxima = bloqueMedidas.ancho_caliente_maximo
		minima = bloqueMedidas.ancho_caliente_minimo
		alta = bloqueMedidas.ancho_caliente_parametro_alto
		baja = bloqueMedidas.ancho_caliente_parametro_bajo
		amarillo = 'warning'
		gris = 'secondary'
		rojo = 'danger'
		color_class = ''

		if maxima and minima and alta and baja:
			if self.ancho_caliente >= baja and self.ancho_caliente <= alta:

corrida/templates/ordenes/lotes.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-left text-info">Lotes </h1>
<h3 class="text-left text-secondary">Seleciona una opción: </h3>    



<table class="table table-sm">
    <!-- ... (contenido de la tabla) ... -->
</table>

<div class="button-group">
    <a class="btn btn-primary mr-2" href="{% url 'corrida:lotes_pendientes' %}">Lotes pendientes</a>
    <a class="btn btn-success mr-2" href="{% url 'corrida:lotes_aprobados' %}">Lotes Aprobados</a>
    <a class="btn btn-danger mr-2" href="{% url 'corrida:lotes_rechazados' %}">Lotes Rechazados</a>
</div>
<br>
<br>
<br>

{% endblock %}

corrida/templates/ordenes/lotes_aprobados.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-left text-info">Lotes Aprobados</h1>
<br>
<h3 class="text-left text-secondary">Seleciona una opción: </h3>    



<table class="table table-sm">
    <!-- ... (contenido de la tabla) ... -->
</table>

<div class="button-group">
    <a class="btn btn-primary mr-2" href="{% url 'corrida:lotes_pendientes' %}">Lotes pendientes</a>
    <a class="btn btn-success mr-2" href="{% url 'corrida:lotes_aprobados' %}">Lotes Aprobados</a>
    <a class="btn btn-danger mr-2" href="{% url 'corrida:lotes_rechazados' %}">Lotes Rechazados</a>
</div>
<br>
{% if no_lotes_aprobados %}
    <div class="alert alert-info" role="alert">
        No hay lotes aprobados en este momento.
    </div>
{% else %}
    <!-- Paginación -->
    <div class="pagination justify-content-center">
        {% if lotes_aprobados.has_previous %}
            <a class="btn btn-light mx-1" href="?page=1">Primero</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="btn btn-light mx-1">Página {{ lotes_aprobados.number }} de {{ lotes_aprobados.paginator.num_pages }}.</span>

        {% if lotes_aprobados.has_next %}
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.next_page_number }}">Siguiente</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.paginator.num_pages }}">Último</a>
        {% endif %}
    </div>
    <br>

    <table class="table table-sm">
        <thead>
            <tr>
                <th class="text-center">No. de Lote</th>
                <th class="text-center">Densidad</th>
                <th class="text-center">Dureza</th>
                <th class="text-center">Flujo de aire</th>
                <th class="text-center">SAG Factor</th>                
                
            </tr>
        </thead>
        <tbody>
            {% for lote in lotes_aprobados %}
                <tr>
                    <td class="text-left">{{ lote.no_de_lote }}</td>
                    <td class="text-center">{{ lote.dureza_capturada }}</td>
                    <td class="text-center">{{ lote.sag_factor_capturado }}</td>
                    <td class="text-center">{{ lote.flujo_de_aire_astm_capturado }}</td>
                    <td class="text-center">{{ lote.densidad_capturada }}</td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginación -->
    <div class="pagination justify-content-center">
        {% if lotes_aprobados.has_previous %}
            <a class="btn btn-light mx-1" href="?page=1">Primero</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="btn btn-light mx-1">Página {{ lotes_aprobados.number }} de {{ lotes_aprobados.paginator.num_pages }}.</span>

        {% if lotes_aprobados.has_next %}
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.next_page_number }}">Siguiente</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_aprobados.paginator.num_pages }}">Último</a>
        {% endif %}
    </div>
    <br>

    {% endif %}

   
<br>

{% endblock %}

corrida/templates/ordenes/lotes_pendientes.html
{% extends "base.html" %}

{% block content %}

<h1 class="text-left text-info">Lotes Pendientes</h1>
<br>
<h3 class="text-left text-secondary">Seleciona una opción: </h3>    



<table class="table table-sm">
    <!-- ... (contenido de la tabla) ... -->
</table>

<div class="button-group">
    <a class="btn btn-primary mr-2" href="{% url 'corrida:lotes_pendientes' %}">Lotes pendientes</a>
    <a class="btn btn-success mr-2" href="{% url 'corrida:lotes_aprobados' %}">Lotes Aprobados</a>
    <a class="btn btn-danger mr-2" href="{% url 'corrida:lotes_rechazados' %}">Lotes Rechazados</a>
</div>
<br>
{% if not lotes_pendientes %}
    <div class="alert alert-info" role="alert">
        No hay lotes pendientes en este momento.
    </div>
{% else %}
    <!-- Paginación -->
    <div class="pagination justify-content-center">
        {% if lotes_pendientes.has_previous %}
            <a class="btn btn-light mx-1" href="?page=1">Primero</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="btn btn-light mx-1">Página {{ lotes_pendientes.number }} de {{ lotes_pendientes.paginator.num_pages }}.</span>

        {% if lotes_pendientes.has_next %}
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.next_page_number }}">Siguiente</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.paginator.num_pages }}">Último</a>
        {% endif %}
    </div>
    <br>

    <table class="table table-sm">
        <thead>
            <tr>
                <th class="text-center">No. de Lote</th>
                <th class="text-center">Densidad</th>
                <th class="text-center">Dureza</th>
                <th class="text-center">Flujo de aire</th>
                <th class="text-center">SAG Factor</th>             
                <th class="text-center">Aprobar</th>
                <th class="text-center">Guardar Linea Selecionada</th>
            </tr>
        </thead>
        <tbody>
            {% for lote in lotes_pendientes %}
                <form action="{% url 'corrida:aprobar_lote' lote.id %}" method="POST">
                {% csrf_token %}
                <tr>
                    <td class="text-left">{{ lote.no_de_lote }}</td>
                    <td class="text-center">
                        <input type="text" size="5" id="densidad_capturada" name="densidad_capturada" value="{{ lote.densidad_capturada }}">
                    </td>
                    <td class="text-center">
                        <input type="text" size="5" id="dureza_capturada" name="dureza_capturada" value="{{ lote.dureza_capturada }}">
                    </td>
                    <td class="text-center">
                        <input type="text" size="5" id="flujo_de_aire_astm_capturado" name="flujo_de_aire_astm_capturado" value="{{ lote.flujo_de_aire_astm_capturado }}">
                    </td>
                    <td class="text-center">
                        <input type="text" size="5" id="sag_factor_capturado" name="sag_factor_capturado" value="{{ lote.sag_factor_capturado }}">
                    </td>                   
                    
                    <td class="text-center">
                        <input class="form-check-input" type="checkbox" name="pruebas_pasadas" id="pruebas_pasadas" {% if lote.pruebas_pasadas %}checked{% endif %}>
                    </td>
                    <td class="text-center">
                        <input type="submit" class="btn btn-success" role="button" value="Guardar Cambios">
                    </td>
                </tr>
                </form>
            {% endfor %}
        </tbody>
    </table>

    <!-- Paginación -->
    <div class="pagination justify-content-center">
        {% if lotes_pendientes.has_previous %}
            <a class="btn btn-light mx-1" href="?page=1">Primero</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="btn btn-light mx-1">Página {{ lotes_pendientes.number }} de {{ lotes_pendientes.paginator.num_pages }}.</span>

        {% if lotes_pendientes.has_next %}
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.next_page_number }}">Siguiente</a>
            <a class="btn btn-light mx-1" href="?page={{ lotes_pendientes.paginator.num_pages }}">Último</a>
        {% endif %}
    </div>
    <br>

{% endif %}

{% endblock %}

corrida/templates/ordenes/ordenes_pendientes.html
{% extends "base.html" %}
{% block content %}


<br>
<br>
<!-- 
<h1 class="text-left my_title text-primary" ><b> Ordenes Pendientes </b></h1>
<br> -->
<!-- <hr class="style1">
    <h3 class="text-left my_title text-info"> <b>Corridas en Producción </b></h3>
    {% for corrida in corridas_en_produccion %}
    <table class="table table-hover" >
        <thead >
            <tr>
            <th class="text-center" > No.Orden</th>
            <th class="text-center" > Tipo de espuma</th>
            <th class="text-center" > Descripcion </th>
            <th class="text-center" > Tipo de unidad </th>
            <th class="text-center" > Forma </th>
            <th class="text-center" > Cantidad </th>
            
            </tr>
        </thead>

        <tbody>
            
           
            {% for elementoCorrida in corrida.elementocorrida_set.all %}

            <tr>
                <td class="text-center" >{{ elementoCorrida.corrida }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.tipo_de_espuma }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.descripcion }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.tipo_de_unidad }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.forma }}</td>
                <td class="text-center" >{{ elementoCorrida.cantidad }}</td>
                
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Area de curado estimada: </td>
                <td>{{ corrida.area_de_curado_estimada }} m<sup>2</sup></td>
            </tr>
        </tbody>
    </table>
    
  
    <hr class="style4">
    <br>
    {% endfor %}
    <hr class="style7">-->
    <br>
    <h1 class="text-right text-secondary"> <b> Ordenes Pendientes </b></h1>
    <br>  
    {% if not corridas_pendientes%}
    <!-- Si no hay corridas pendientes -->
    <div>
        <div class="text-center">
            <br>
            <br>
            <h2 class="text-center my_title">
                No hay ordenes Pendientes actualmente.
            </h2>
            <br>
            <br>
        </div>
    </div>
    {% else %}
    <!-- <h3 class="text-left my_title text-info" > <b> Corridas Pendientes </b></h3> -->
    {% for corrida in corridas_pendientes %}
    <h3>No de orden: {{corrida.id}}</h3>
    <h3>Fecha programada: {{corrida.fecha_programada.date}}</h3>
    <h3 class="text-info" >Cedis : <b> {{corrida.cedis}} </b></h3>
    <table class="table table-hover table-sm" >
        <thead>
            <tr>
            <th class="text-center"> Tipo de espuma</th>
            <th class="text-center"> Descripcion </th>
            <th class="text-center"> Tipo de unidad </th>
            <th class="text-center"> Forma </th>
            <th class="text-center"> Cantidad </th>
            <th class="text-center"> Remover </th>
            </tr>
        </thead>

        <tbody>
            <form action="{% url 'corrida:editar_cantidades_corrida' %}" method="POST">
              {% csrf_token %}
            {% for elementoCorrida in corrida.elementocorrida_set.all %}

            <tr>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.tipo_de_espuma.tipo_de_espuma }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.descripcion }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.tipo_de_unidad }}</td>
                <td class="text-center" >{{ elementoCorrida.bloqueMedidas.forma }}</td>
                <td class="text-center" >
                    <input type="text" size="5" id="{{elementoCorrida.cantidad}}" name="cantidades" value="{{ elementoCorrida.cantidad }}">
                    <input type="hidden" id ="{{elementoCorrida.id}}" name="elementoIds" value="{{elementoCorrida.id}}">
                </td>
                <td class="text-center" >
                    <a class="btn btn-danger" href="{% url 'corrida:remover_elemento_corrida' elementoCorrida.id %}" role="button"> Remover  </a>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>Area de curado estimada: </td>
                <td>{{ corrida.area_de_curado_estimada }} m<sup>2</sup></td>
            </tr>
        </tbody>
    </table>
    <!-- este boton de summit truena  input type="submit" class="btn btn-warning" value="Producir Orden" -->
    <a class="btn btn-success" href="{%url 'corrida:producir_corrida' corrida.id %}" role="button"> Producir Orden  </a>
    <a class="btn btn-info" href="{% url 'corrida:cancelar_corrida' corrida.id %}" role="button"> Cancelar  </a>
    <input type="submit" class="btn btn-warning" value="Cambiar Cantidades">
    </form>
    <hr class="style4">
    <br>
    {% endfor %}
    {% endif %}


   
{%endblock%}